### ISSUE TITLE
`yum-builddep` pipeline step failing due to vault.centos.org connection issues

### ISSUE THREAD

**Issue by jbartak** [iuscommunity/infrastructure#26]
Hi, I've spotted that my [changes](https://github.com/iusrepo/phpMyAdmin49/pull/9) to the [phpMyAdmin49](https://github.com/iusrepo/phpMyAdmin49) IUS repo have [failed in Cirrus](https://cirrus-ci.com/task/5114989483655168?logs=builddep#L14) during the package build. It looks like there is a problem with CentOS mirrors:
```
http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2a05:d018:117:3001:e7bb:ad90:ec3e:2e61: Cannot assign requested address"
Trying other mirror.
http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2a05:d018:117:3001:e7bb:ad90:ec3e:2e61: Cannot assign requested address"
Trying other mirror.
http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: [Errno 14] HTTPS Error 301 - Moved Permanently
Trying other mirror.
failure: repodata/repomd.xml from base-source: [Errno 256] No more mirrors to try.
http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2a05:d018:117:3001:e7bb:ad90:ec3e:2e61: Cannot assign requested address"
http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2a05:d018:117:3001:e7bb:ad90:ec3e:2e61: Cannot assign requested address"
http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: [Errno 14] HTTPS Error 301 - Moved Permanently
```

**Comment by jeffsheltren** [comment]
Thanks for the report! I just pushed an empty commit to trigger another build of the package and it has gotten past the builddep step that the previous build failed on. Seems perhaps a transient issue? 

https://cirrus-ci.com/build/6238617042419712

**Comment by carlwgeorge** [comment]
Thanks for triggering the rebuild Jeff.  The issue here is that the [`yum build-dep` step](https://github.com/iusrepo/phpMyAdmin49/blob/main/.cirrus.yml#L21) of our pipeline automatically enables all system repos matching `*-source`.  In the centos:7 container we're using, those use http://vault.centos.org, which is heavily overloaded lately due to the CentOS 8 EOL.  If the problem persists we can add a step in our pipeline to switch from http://vault.centos.org to https://mirror.rackspace.com/centos-vault/.

**Comment by lubo** [comment]
Looks like the packages are still not in the repository though.

**Comment by jeffsheltren** [comment]
Thanks @carlwgeorge -- seems like this is ongoing, I just hit it with a [php74 build](https://cirrus-ci.com/task/5152924203483136).


Regarding
> Looks like the packages are still not in the repository though.

I haven't pushed those packages because I haven't touched the phpMyAdmin49 repo previously and didn't want to step on someone else's process. Who has pushed them previously?

**Comment by carlwgeorge** [comment]
I pushed the build in question (phpMyAdmin49-4.9.8-1.el7.ius) to the testing repo.

**Comment by carlwgeorge** [comment]
The php74 build is getting a different error.  It seems `yum-builddep` doesn't follow 301 redirects, and the http vault links are now redirecting to https vault links.  The centos:7 repo definitions will need to be updated, but in the short term the fix is the same for us, adding a sed in the pipeline to modify the source repo urls.

**Comment by carlwgeorge** [comment]
Here is the fix I applied to the build pipeline for php74.

https://github.com/iusrepo/php74/commit/8aeeb7e0dd0755feb3e086349df0d2c2c7cdc8f7

Any other build failures can use this same fix.  I went ahead and published that php74 build to the testing repos.

**Comment by carlwgeorge** [comment]
The IUS project has reached it's end of life, and will not be addressing any more issues or pull requests.

ius.io/faq#why-doesnt-ius-have-packages-for-rhel-8

iusrepo/announce#41
